#!/bin/bash
#This script migrates djangopostres

yum -y install python-pip
pip install virtualenv
pip install --upgrade pip

#make a dir on root called myproject, cd into it, activate, and run from inside 
mkdir ~/myproject
cd ~/myproject
virtualenv myprojectenv

#
source myprojectenv/bin/activate
pip install django psycopg2
django-admin.py startproject myproject .



wget -O ~/myproject/myproject/settings.py https://github.com/Hoangdinh85/NTI-310/blob/master/settings.py

python manage.py makemigrations
python manage.py migrate


for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios-a );  do gcloud compute ssh --zone us-east4-c hdinh47056@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/Hoangdinh85/NTI-310/master/nagios-client && sudo bash nagios-client'; done
