#!/bin/bash
#This script migrates djangopostres

yum -y install python-pip
pip install virtualenv
pip install --upgrade pip

#make a dir on root called myproject, cd into it, activate, and run from inside 
mkdir ~/myproject
cd ~/myproject
virtualenv myprojectenv

#
source myprojectenv/bin/activate
pip install django psycopg2
django-admin.py startproject myproject .



wget -O ~/myproject/myproject/settings.py https://raw.githubusercontent.com/Hoangdinh85/NTI-320/master/settings.py

python manage.py makemigrations
python manage.py migrate

#setting up machine to run as rsyslog client to server rsyslog
#install this on a server
#rsyslog should be first server run up
#rsyslog client automation
sudo yum -y install && yum -y update rsyslog
sudo systemctl start rsyslog
sudo systemctl enable rsyslog

#needs to be the name of the client rsyslog server
echo "*.*@@rsyslog:514" >> /etc/rsyslog.conf
#systemctl restart rsyslog
#systemctl enable rsyslog
